image: golang
pipelines:
  default:
    - step:
        name: GoImports
        script:
          - mkdir -p /go/src/bitbucket.org/atlassian/stridestats
          - cp -R ./* /go/src/bitbucket.org/atlassian/stridestats
          - go get -u golang.org/x/tools/cmd/goimports
          - if [[ "$(goimports -l -d .)" != "" ]]; then echo "$(goimports -l -d .)" && exit 1; fi
    - step:
        name: Metalinter
        script:
          - go get -u github.com/alecthomas/gometalinter
          - gometalinter --install --update
          - gometalinter --vendor --disable-all --enable=vet --enable=vetshadow --enable=golint --enable=ineffassign --enable=goconst --tests .
    -step:
        name: Tests
        script:
          - curl https://glide.sh/get | sh
          - glide up
          - echo '# Generate coverage report and test for race conditions'
          - go test -race -cover
